export const staffs = [
  {
    id: 1,
    name: "Dr.Vairamuthu S",
    email: "Example.gmail.com",
    image:
      "https://vit.ac.in/system/files/styles/facultyfilter/private/Vairamuthu-11190.jpg?itok=Y0OluPKe",
    designation: "Associate Professor & HOD",
    college: "VIT Chennai",
    department: "softwareSystems",
  },
  {
    id: 2,
    name: "Dr.Jaisankar N",
    email: "Example.gmail.com",
    image: "https://vit.ac.in/sites/default/files/schools/faculty/10247.jpg",
    designation: "Associate Professor & HOD",
    college: "VIT Chennai",
    department: "softwareSystems",
  },
  {
    id: 3,
    name: "Dr. Arun Kumar G",
    email: "Example.gmail.com",
    image: "https://vit.ac.in/sites/default/files/schools/faculty/12372.jpg",
    designation: "Associate Professor & HOD",
    college: "VIT Chennai",
    department: "softwareSystems",
  },
  {
    id: 4,
    name: "Dr.Anthoniraj A",
    email: "Example.gmail.com",
    image:
      "https://vit.ac.in/system/files/styles/facultyfilter/private/antony.png?itok=MDu4dTh9",
    designation: "Associate Professor & Director - SDC",
    college: "VIT Chennai",
    department: "softwareSystems",
  },

  {
    id: 5,
    name: "Dr.Parveen Sultana H",
    email: "Example.gmail.com",
    image: "https://vit.ac.in/sites/default/files/schools/faculty/10435.jpg",
    designation: "Associate Professor & HOD",
    college: "VIT Chennai",
    department: "softwareSystems",
  },
  {
    id: 6,
    name: "Dr.Arunkumar T",
    email: "Example.gmail.com",
    image:
      "https://vit.ac.in/sites/default/files/styles/facultyfilter/public/10708.jpg",
    designation: "Professor",
    college: "VIT Chennai",
    department: "analytics",
  },
  {
    id: 7,
    name: "Dr.Kannan A",
    email: "Example.gmail.com",
    image: "https://vit.ac.in/sites/default/files/schools/faculty/15883.jpg",
    designation: "Senior Professor & HOD",
    college: "VIT Chennai",
    department: "iot",
  },
  {
    id: 8,
    name: "Dr.Vasantha W B",
    email: "Example.gmail.com",
    image: "https://vit.ac.in/sites/default/files/schools/faculty/15194.jpg",
    designation: "Professor",
    college: "VIT Chennai",
    department: "softwareSystems",
  },
  {
    id: 9,
    name: "Dr.Ananda Kumar S",
    email: "Example.gmail.com",
    image:
      "https://vit.ac.in/sites/default/files/styles/facultyfilter/public/11872.jpg?itok=cmLgIey9",
    designation: "Associate Professor",
    college: "VIT Chennai",
    department: "computationalIntelligence",
  },
  {
    id: 10,
    name: "Dr.Abdul Gaffar H",
    email: "Example.gmail.com",
    image: "https://vit.ac.in/sites/default/files/schools/faculty/11473.jpg",
    designation: "Associate Professor",
    college: "VIT Chennai",
    department: "databaseSystems",
  },
  {
    id: 11,
    name: "Dr.Sathyaraj R",
    email: "Example.gmail.com",
    image:
      "https://vit.ac.in/sites/default/files/styles/facultyfilter/public/12425.jpg?itok=3zkxTEVi",
    designation: "Associate Professor & HOD",
    college: "VIT Chennai",
    department: "informationSecurity",
  },
  {
    id: 12,
    name: "Dr.Kalyanaraman P",
    email: "Example.gmail.com",
    image: "https://vit.ac.in/sites/default/files/schools/faculty/10084.jpg",
    designation: "Professor",
    college: "VIT Chennai",
    department: "informationSecurity",
  },
  {
    id: 13,
    name: "Dr.Madhu Viswanatham V",
    email: "Example.gmail.com",
    image:
      "https://vit.ac.in/sites/default/files/styles/facultyfilter/public/10704.jpg?itok=OX5TkA32",
    designation: "Professor",
    college: "VIT Chennai",
    department: "informationSecurity",
  },
  {
    id: 14,
    name: "Dr.Saravanan R",
    email: "Example.gmail.com",
    image: "https://vit.ac.in/sites/default/files/schools/faculty/10230.jpg",
    designation: "Associate Professor",
    college: "VIT Chennai",
    department: "informationSecurity",
  },
  {
    id: 15,
    name: "Dr.Manikandan K",
    email: "Example.gmail.com",
    image: "https://vit.ac.in/sites/default/files/schools/faculty/10910.jpg",
    designation: "Associate Professor",
    college: "VIT Chennai",
    department: "databaseSystems",
  },
];
